# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  binary: proxy
  id: loxone-weather-proxy
  goos:
    - linux
  goarch:
    - amd64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
dockers:
  - image_templates:
      - 'samvdb/loxone-weather-proxy:{{ .Tag }}'
      - 'samvdb/loxone-weather-proxy:v{{ .Major }}.{{ .Minor }}'
      - 'samvdb/loxone-weather-proxy:latest'
    dockerfile: Dockerfile
    ids:
      - proxy
    build_flag_templates:
      - "--pull"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      linux: Linux
      amd64: x86_64
