# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: linux-amd64
    binary: proxy-linux-{{ .Arch }}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
dockers:
  - image_templates:
      - 'ghcr.io/samvdb/{{ .ProjectName }}:{{ .Tag }}'
      - 'ghcr.io/samvdb/{{ .ProjectName }}:latest'
    dockerfile: Dockerfile
#    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}


