# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  binary: proxy
  id: loxone-weather-proxy
  goos:
    - linux
  goarch:
    - amd64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
dockers:
  - image_templates:
      - 'ghcr.io/samvdb/{{ .ProjectName }}:{{ .Tag }}'
      - 'ghcr.io/samvdb/{{ .ProjectName }}:latest'
    dockerfile: Dockerfile
    ids:
      - loxone-weather-proxy
    build_flag_templates:
      - --platform=linux/amd64

